### ISSUE TITLE
Signature check failing

### ISSUE THREAD

**Issue by Belphemur** [DNSCrypt/dnscrypt-resolvers#148]
Hello @jedisct1,

It seems the latest commit didn't contain the right signature.

Travis is saying the signature is wrong.

**Comment by jedisct1** [comment]
Hi!

The signature is fine. Travis just required a restart 😊

**Comment by jedisct1** [comment]
The clarify, the issue is due to Github asset caching.

It takes a couple seconds (minutes?) for a change to an existing file to propagate to the GitHub CDN.

So, when the signature is added a Travis runs right after, the old version of the file is still the one publicly visible, i.e. the one that Travis loads.

Which is why it constantly fails after a signature update, and restart the job makes Travis happy again.

That should be pretty easy to fix, manually loading the files and trying to bypass the cache.
