### ISSUE TITLE
New public server addition

### ISSUE THREAD

**Issue by dct-infra** [DNSCrypt/dnscrypt-resolvers#490]
Hi!

I've been playing with dnscrypt-proxy and e-dns server for a few days now. Thank you Franck and everyone involved for these good useful projects.

I would like to contribute by adding a first long term server to the public dns resolvers list.

What information is needed apart from the stamp, location and server policies?

Thanks!

**Comment by jedisct1** [comment]
Hi!

You can add any information you like to the server description, including links. But there's just one little but important thing missing from your list: the name :)

The is the name people will configure in order to connect to your server.

Then, the most convenient way to add a server is to submit a pull request. Only the `v3/public-resolvers.md` file needs to be modified; the other ones will be automatically updated.

**Comment by dct-infra** [comment]
Hey,

I just made a pull request (before reading your post), v2 **and** v3 were updated. Hope it's not an issue.

**Comment by jedisct1** [comment]
Not a problem at all!
