### ISSUE TITLE
Server stamps with issues

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-resolvers#614]
Extracted from the log file, should those stamps be updated?

 - [CRITICAL] [adguard-dns-doh]
     - Certificate hash [`ac15d221c58f955a879da52ac42960216811158fef0bfa9fc5265eb03293ee7e`] not found
 - [CRITICAL] [adguard-dns-family-doh]
     - Certificate hash [`ac15d221c58f955a879da52ac42960216811158fef0bfa9fc5265eb03293ee7e`] not found
 - [CRITICAL] [tuna-doh-ipv4]
     - Certificate hash [`ad6aa4176b5386d8511f619ddb40b9abbadda4dd7fc17364db614483fdcca847`] not found
 - [WARNING] [adguard-dns-family]
    - uses a non-standard provider name ('`2.dnscrypt.family.ns1.adguard.com.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [adguard-dns-unfiltered]
    - uses a non-standard provider name ('`2.dnscrypt.unfiltered.ns1.adguard.com.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [adguard-dns]
    - uses a non-standard provider name ('`2.dnscrypt.default.ns1.adguard.com.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [cleanbrowsing-adult]
    - uses a non-standard provider name ('`cleanbrowsing.org.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [cleanbrowsing-security]
    - uses a non-standard provider name ('`cleanbrowsing.org.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [dnsforfamily-no-safe-search]
    - uses a non-standard provider name ('`dnsforfamily.com.`' doesn't start with '`2.dnscrypt-cert.`')
 - [WARNING] [dnsforfamily]
    - uses a non-standard provider name ('`dnsforfamily.com.`' doesn't start with '`2.dnscrypt-cert.`')

I checked https://dnscrypt.info/stamps-specifications/, but didn't get what a provider name is really for.

**Comment by jedisct1** [comment]
The provider name can be anything that represents a DNS servers operator. Multiple servers run by the same person can share the same name, so they don't need to manage multiple certificates.

The `2.dnscrypt-cert.` prefix is required for DNSCrypt v2, and to support anonymized queries.

We can't change that information in the list; AdGuard and DNSForFamily would have to do it, but it then all the clients configurations would need to be updated. They're unlikely to do it :(

DoH servers that changed certificate providers have to be fixed in the list, though.

**Comment by jedisct1** [comment]
These should have been fixed.

Thanks for the heads up!
