### ISSUE TITLE
OpenWrt https-dns-proxy

### ISSUE THREAD

**Issue by stokito** [DNSCrypt/dnscrypt-resolvers#842]
The OpenWrt is an open source firmware for routers and RPi.
There is a [https_dns_proxy](https://github.com/aarond10/https_dns_proxy) package with a GUI for Luci admin panel.
And it needs for a list of servers to show to users.
Currently they all are stored in JSON files
https://github.com/openwrt/luci/tree/master/applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers

But ideally it would be great to just fetch the list from your repo.
I already [proposed this](
https://github.com/openwrt/luci/pull/6546?notification_referrer_id=NT_kwDOAAZXDrE3NTQ0NzI5MzI2OjQxNTUwMg&notifications_query=is%3Adone#issuecomment-1703962340).

One of the problems is that here data is stored in Markdown files and not JSON.
Maybe that's not a big deal and we can just parse them with few lines of JS but the md files must follow strict rules.
I believe that the page https://dnscrypt.info/public-servers/ is generated automatically, right?
Can we you make JSON files or write a JS function to parse the MD files that will not changed and used safelly.

Also some data may be missing here but already exists in the https-dns-proxy/providers.
Could you please check and merge data?

CC @stangri

**Comment by jedisct1** [comment]
The `dnscrypt-proxy -list-all -json` command outputs the entire server list from the configured sources as a JSON file.

That command is used to automatically update the file loaded to display the map, that can be downloaded here:

https://download.dnscrypt.info/dnscrypt-resolvers/json/

**Comment by stokito** [comment]
Thank you @jedisct1 this is really great! How stable is this link? Can we rely on it and use it in software? I see that it has CORS headers so probably we can fetch the list just from UI.

Hi @tina-hello I see that you are maintaining the list https://github.com/curl/curl/wiki/DNS-over-HTTPS
Maybe you can merge your efforts with this project?


Hi @saradickinson you are also maintaining a list of DoH provider https://github.com/dnsprivacy/dnsprivacy.github.io/tree/main/public_resolvers
So you should be interested in the topic.

**Comment by tina-hello** [comment]
@stokito Thanks for the info, but this project is more geared toward dnscrypt users, especially since the name & DNS stamps are only useful on apps that support them (aside from dnscrypt, I think AdGuard & Yandex is the only one that use them). The curl wiki meanwhile just list plain DoH URLs to be pasted on browsers or other app. It would also take more effort for me to check the log policy, location, generating stamps etc, while for curl wiki I just run a script to check if any servers are down and test if a new server I found has adult/ad filtering.

**Comment by stokito** [comment]
👍 thank you for the clarification

**Comment by jedisct1** [comment]
This list of public encrypted resolvers has been maintained since 2011, and keeps being constantly updated. The liveliness of its entries is also actively monitored.

It's not specifically for DNSCrypt, as it also includes DoH/DoH/ODoH and soon DoOH servers and relays. DNS Stamps were made to represent the information needed for these different protocols.

The JSON URL is stable. It has never changed, it's used by the website to print the list and map, and I know that quite a few projects are using it directly, so it's not going to change.

**Comment by Brueggus** [comment]
> One of the problems is that here data is stored in Markdown files and not JSON.

There's also an (auto-generated) list of dnscry.pt resolvers available at https://www.dnscry.pt/resolvers.json in case that's useful for anyone.
