### ISSUE TITLE
stamp

### ISSUE THREAD

**Issue by huv9** [DNSCrypt/dnscrypt-resolvers#925]
hi Frank
Duplicates found In resolvers and relays

## scaleway-ams

DNSSEC/Non-logged/Uncensored in Germany
Maintained by Frank Denis - https://fr.dnscrypt.info

sdns://AQcAAAAAAAAADDY1LjIxLjIyOC40OCDQxXrwNIgFGirfU35Ph3G3yHrKjSOWuRc6VnbuWRTLxRcyLmRuc2NyeXB0LWNlcnQuaGV0em5lcg

## scaleway-fr

DNSSEC/Non-logged/Uncensored in Germany
Maintained by Frank Denis - https://fr.dnscrypt.info

sdns://AQcAAAAAAAAADDY1LjIxLjIyOC40OCDQxXrwNIgFGirfU35Ph3G3yHrKjSOWuRc6VnbuWRTLxRcyLmRuc2NyeXB0LWNlcnQuaGV0em5lcg

## anon-scaleway-ams

Anonymized DNS relay hosted in Amsterdam and maintained by Frank Denis (@jedisct1).

sdns://gRA2NS4yMS4yMjguNDg6NDQz

## anon-scaleway

Anonymized DNS relay hosted in France and maintained by Frank Denis (@jedisct1).

sdns://gRA2NS4yMS4yMjguNDg6NDQz

my regards

**Comment by jedisct1** [comment]
Hi,

Yes, this is a temporary hack.

Scaleway suddenly shut down all my servers, with no option to turn them back up again.

In order to get some service continuity for people who where previously using them, I set up an emergency server elsewhere, and pointed all `scaleway-*` and `crypto.sx` servers to it.

The situation seems to have been resolved, the servers are back, but I want to wait a few days before restoring the previous stamps, just in case.

**Comment by huv9** [comment]
> Hi,
> 
> Yes, this is a temporary hack.
> 
> Scaleway suddenly shot down all my servers, with no option to turn them back up again.
> 
> In order to get some service continuity for people who where previously using them, I set up an emergency server elsewhere, and pointed all `scaleway-*` and `crypto.sx` servers to it.
> 
> The situation seems to have been resolved, the servers are back, but I want to wait a few days before restoring the previous stamps, just in case.

Thank you for the clarification
